---
title: "Loading Metadata Report"
author: ""
date: '`r Sys.Date()`'
output:
  html_document:
    df_print: "paged"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries}
# Dependencies
library(NIHSnmr)
requireNamespace("purrr")
requireNamespace("readxl")
requireNamespace("htmltools")
requireNamespace("DT")
```


```{r default-values}
# These should be defined in the environment that calls rmarkdown::render
if (!exists("nmr_dataset")) {
  stop("nmr_dataset should be defined before running this notebook")
  nmr_dataset <- NULL # to make linter happy
}
if (!exists("excel_file")) {
  stop("excel_file should be defined before running this notebook")
  excel_file <- NULL # to make linter happy
}
if (!exists("xlsx_file")) {
  stop("xlsx_file should be defined before running this notebook")
  xlsx_file <- NULL # to make linter happy
}
if (!exists("nmr_dataset_outfile")) {
  stop("nmr_dataset_outfile should be defined before running this notebook")
  nmr_dataset_outfile <- NULL # to make linter happy
}
```


## xlsx Input files

These are the input metadata tables that will be integrated:

```{r read-input}
excel_dfs <- excel_file %>% 
  readxl::excel_sheets() %>%
  purrr::map(~readxl::read_excel(path = excel_file, sheet = .))
```


```{r print-input}
excel_dfs %>%
  purrr::map(DT::datatable) %>%
  htmltools::tagList()
```


## The added and linked metadata

```{r integrate-metadata}
for (excel_df in excel_dfs) {
  # If the sheet is empty, skip
  if (nrow(excel_df) == 0 || ncol(excel_df) == 0) {
    # Empty sheet
    next
  }
  # Check that the key column is already in the metadata:
  key_column <- colnames(excel_df)[1]
  avail_columns <- colnames(nmr_meta_get(nmr_dataset, groups = "external"))
  if (!key_column %in% avail_columns) {
    stop(glue::glue("Key Column {key_column} is not present in the metadata.",
                    "Can't add metadata.\n Available columns:",
                    glue::glue_collapse(avail_columns, sep = ", ", last = " and ")))
  }
  # The NMRExperiment column should of type character, although Excel may use numeric
  # because usually all the identifiers are numeric. We convert it manually:
  if ("NMRExperiment" %in% colnames(excel_df)) {
    excel_df$NMRExperiment <- as.character(excel_df$NMRExperiment)
  }
  # Add the metadata
  nmr_dataset <- nmr_add_metadata(nmr_dataset, metadata = excel_df, by = key_column)
}
```

```{r print-output}
nmr_export_metadata(nmr_dataset, xlsx_file, groups = "external")
nmr_dataset_save(nmr_dataset, nmr_dataset_outfile)
nmr_dataset %>%
  nmr_meta_get(groups = "external") %>%
  DT::datatable()
```

